### ISSUE TITLE
Any test data available?

### ISSUE THREAD

**Issue by mhoehle** [mfranberg/besiq#2]
The Readme file in the section "For the impatient" contains the following block:

> ls /data/
dataset.pair
dataset.bim
dataset.fam
dataset.bed

So these data apparently are located outside the project, so as an outsider it's not possible to run this - hence, this is unfortunately not very helpful.  I understand that some data cannot be shared, but I definitely miss a statement about this in the README file. Furthermore, it would be nice to include any real "trial" data as part of the program so I could at least try out the software? :-(

**Comment by mfranberg** [comment]
This is a very good idea! I generated some fake data, it is now in the data folder (as part of ac4a5660cfd1a10468bb545fe11375a6dacd7ef3)

**Comment by mhoehle** [comment]
Great thanks, worked for me now. Depending on time and user: You might want to adapt the new location of the data for the code example of the section "for the impatient".

**Comment by mfranberg** [comment]
Thank you again, updated in d42b5479be533c7107ab267b6c5b3129db4f2aed.
