### ISSUE TITLE
Compiling on mac os

### ISSUE THREAD

**Issue by mhoehle** [mfranberg/besiq#3]
Running on Mac OS X 10.14.4 I installed the Armadillo pkg through homebrew:

brew install armadillo

Then the cmake worked alright. However, when running "make" I ran into the following problem:

Scanning dependencies of target gene_environment
[ 67%] Building CXX object src/CMakeFiles/gene_environment.dir/gene_environment.cpp.o
clang: error: no such file or directory: 'NOTFOUND'
make[2]: *** [src/CMakeFiles/gene_environment.dir/gene_environment.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/gene_environment.dir/all] Error 2
make: *** [all] Error 2

When looking at flags.make in the gene_environment folder I saw the following:

<snip>
CXX_FLAGS =  -std=c++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk NOTFOUND
</snip>
I have no clue how the NOTFOUND ended up there. It's also in the link.txt. Had to manually delete it in the two files and then this part worked. There were 2-3 more folders where I had to do the same: remove NOTFOUND in CXX_FLAGS of flags.make and in link.txt. Then it compiled. 

Any idea where this came from? It's not important, in particular because it looks like a Mac specific problem, but maybe others running into the same problem might benefit from this issue.

**Comment by mfranberg** [comment]
Thank you for reporting this, It seems like the way OpenMP is included has changed on OS X. I have submitted a patch now that should work (14df889ee634a1ed2c3245e06e85b61416d43083). Sorry for the inconvenience :(

**Comment by mhoehle** [comment]
Thanks, works now!
